language: php
matrix:
  include:
  - php: 7.3
    env: PREFER_LOWEST=""
  - php: 7.1
    env: PREFER_LOWEST=""
#  - php: 7.1
#    env: PREFER_LOWEST="--prefer-lowest"

before_script:
- composer update $PREFER_LOWEST --no-interaction
script:
#- "./vendor/bin/phpunit"
#- "./vendor/bin/composer-require-checker --config-file=composer-require-checker.json"
- composer cs-check
- composer phpstan
